### ISSUE TITLE
Bot keeps queue 

### ISSUE THREAD

**Issue by wzc-Seer** [wezacon/dbos#12]
**Describe the bug**
The song stays in the queue when the bot is kicked from the voicechannel

**To Reproduce**
1. Use db.play (URL)
2. Disconnect the bot forcefully
3. Use db.play (URL)
4. The bot is now broken

**Expected behavior**
The bot will be broken in the server for the time that it is online

**Comment by ABotDev** [comment]
F

**Comment by nickdevnl** [comment]
F

**Comment by wzc-Seer** [comment]
Lmfao daar heb ik veel aan-

**Comment by nickdevnl** [comment]
Kijken we nog wel naar is niet enorm moeilijk denk

**Comment by nickdevnl** [comment]
should be fixed in #13

**Comment by nickdevnl** [comment]
btw the bot will be broken untill queue ends

**Comment by wzc-ElishaZ** [comment]
Debugged.

**Comment by wzc-ElishaZ** [comment]
testing to see if it works on 2 servers at once

**Comment by wzc-ElishaZ** [comment]
Debugged x2
