### ISSUE TITLE
Clear user bios for Admins

### ISSUE THREAD

**Issue by Slimakoi** [wezacon/dbos#4]
Have an dbos admin command where you can clear the bio of an specific user, when done so, it would clear the bio and send a notification to the user informing them that their bio has been cleared. This would be useful for inappropriate bios for global bios, blacklist and server bios, where the admins of the server can clear them.

Command example: `db.bioclear [global/server id/nothing] [user id] [reason]`

**Comment by wzc-Seer** [comment]
Will be working on it!

**Comment by wzc-Seer** [comment]
The feature has been added into version: 2.2.2!
