### ISSUE TITLE
oh yh add help docs

### ISSUE THREAD

**Issue by LoadxWar** [wezacon/dbos#6]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wzc-Seer** [comment]
Can you please explain this more @LoadxWar ?

**Comment by LoadxWar** [comment]
> Can you please explain this more @LoadxWar ?

**Comment by wzc-Seer** [comment]
@LoadxWar 
I am currently working on this!

**Comment by wzc-Seer** [comment]
A basic help doc was added, this can be improved with pull requests!
