### ISSUE TITLE
Manual deletion

### ISSUE THREAD

**Issue by Slimakoi** [wezacon/dbos#9]
Basically people could delete their data from the server entirely if they had privacy conserns

**Comment by gastrodon** [comment]
Thanks for creating the issue for me.

I think that, going off of privacy concerns, any bot should ask _before_ collecting or listing data. It should never be the responsibility of the user. This is atypical of any service, especially one that some user does not seek themselves. It raises serious privacy questions in my opinion

**Comment by Slimakoi** [comment]
I understand and completely agree with you, but correct me if im wrong but
I personally don't think that nicknames and avatars aren't considered to be
private information, but message count maybe in a way.

**Comment by gastrodon** [comment]
I think that the primary issue is that the bot is making that information public (at least, it appears to me, since I was linked to a page with my information)

**Comment by Slimakoi** [comment]
The bot has a page listing all the servers and the members in it yes

**Comment by wzc-Seer** [comment]
This will be worked on this afternoon asap, a new command will be added for this, please be patient though!

**Comment by wzc-Seer** [comment]
A new feature has been added to get rid of this problem, now introducing: **(prefix)userdata** make sure to use that as it is more powerfull then the remove.
